app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern:  /login_check

fos_user_security_logout:
    pattern:  /logout
