app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security_login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:  /login_check

fos_user_security_logout:
    path:  /logout
